# 世界の最新の感染者数

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
del df["Lat"]
del df["Long"]

In [3]:
df.head()

Province/State Country/Region  1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  \
0            NaN    Afghanistan        0        0        0        0        0   
1            NaN        Albania        0        0        0        0        0   
2            NaN        Algeria        0        0        0        0        0   
3            NaN        Andorra        0        0        0        0        0   
4            NaN         Angola        0        0        0        0        0   

   1/27/20  1/28/20  1/29/20  ...  5/19/21  5/20/21  5/21/21  5/22/21  \
0        0        0        0  ...    64122    64575    65080    65486   
1        0        0        0  ...   132095   132118   132153   132176   
2        0        0        0  ...   125896   126156   126434   126651   
3        0        0        0  ...    13569    13569    13569    13569   
4        0        0        0  ...    31438    31661    31909    32149   

   5/23/21  5/24/21  5/25/21  5/26/21  5/27/21  5/28/21  
0    65728    66275    66903    67743    68366    69130  
1   132209   132215   132229   132244   132264   132285  
2   126860   127107   127361   127646   127926   128198  
3    13569    13569    13664    13671    13682    13693  
4    32441    32623    32933    33338    33607    33944  

[5 rows x 495 columns]

In [4]:
latest_date = df.tail(1).columns[-1]
latest_date

'5/28/21'

In [5]:
latest_column_key = df.columns[-1]
df = df[['Province/State','Country/Region',latest_column_key]]
df = df.rename(columns={latest_column_key:"latest_confirmed"})
df.head()

Province/State Country/Region  latest_confirmed
0            NaN    Afghanistan             69130
1            NaN        Albania            132285
2            NaN        Algeria            128198
3            NaN        Andorra             13693
4            NaN         Angola             33944

## 全世界の最新の感染者数

In [6]:
print("全世界感染者数({}時点):{:,}人".format(latest_date,df["latest_confirmed"].sum()))

全世界感染者数(5/28/21時点):169,470,725人


## 国別の最新の感染者数

In [7]:
country = df.groupby(["Country/Region"],as_index=False).sum("latest_confirmed")
country = country.sort_values("latest_confirmed", ascending=False)

In [8]:
country.head()

Country/Region  latest_confirmed
179             US          33239963
79           India          27729247
23          Brazil          16391930
62          France           5708350
178         Turkey           5228322

In [9]:
import matplotlib.pyplot as plt
%matplotlib notebook
#%matplotlib inline

In [10]:
plt.figure(figsize=(9.5,5))
plt.title("Worst 50")
plt.xticks(rotation="90",fontsize=9)
plt.ylabel("count (1000 people)")
#fig.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))
plt.bar(country.head(50)["Country/Region"],country.head(50)["latest_confirmed"]/1000,label="positive")
plt.legend()
plt.tight_layout()

<IPython.core.display.Javascript object>

## ヒストグラム 

In [11]:
plt.figure(figsize=(10,5))
plt.title("histgram(million)")
#plt.xticks(rotation="90",fontsize=9)
#plt.ylabel("count (1000 people)")
#fig.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))
plt.hist(country["latest_confirmed"]/1000000,bins=20)

<IPython.core.display.Javascript object>

(array([174.,   7.,   6.,   3.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,
          0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   1.]),
 array([1.00000000e-06, 1.66199910e+00, 3.32399720e+00, 4.98599530e+00,
        6.64799340e+00, 8.30999150e+00, 9.97198960e+00, 1.16339877e+01,
        1.32959858e+01, 1.49579839e+01, 1.66199820e+01, 1.82819801e+01,
        1.99439782e+01, 2.16059763e+01, 2.32679744e+01, 2.49299725e+01,
        2.65919706e+01, 2.82539687e+01, 2.99159668e+01, 3.15779649e+01,
        3.32399630e+01]),
 <a list of 20 Patch objects>)

## 人口当たりの分析

In [12]:
pop = pd.read_excel("world-data/WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES.xlsx",header=16)
pop.head(1)

Index    Variant Region, subregion, country or area * Notes  Country code  \
0      1  Estimates                                WORLD   NaN           900   

    Type  Parent code         1950         1951        1952  ...         2011  \
0  World            0  2536431.018  2584034.227  2630861.69  ...  7041194.168   

          2012         2013         2014         2015         2016       2017  \
0  7125827.957  7210582.041  7295290.759  7379796.967  7464021.934  7547858.9   

          2018         2019         2020  
0  7631091.113  7713468.205  7794798.729  

[1 rows x 78 columns]

In [13]:
pop.iloc[:,-1]

0      7794798.729
1              ...
2      1273304.261
3      6521494.468
4      1057438.163
          ...     
284         62.273
285      37742.157
286         56.772
287          5.795
288     331002.647
Name: 2020, Length: 289, dtype: object

In [14]:
pop_latest = pop.loc[pop["Type"]=="Country/Area"][[pop.columns[2],pop.columns[-1]]]

In [15]:
pop_latest.columns = ["country","population"]

In [16]:
pop_latest.head()

country  population
26   Burundi   11890.781
27   Comoros     869.595
28  Djibouti     988.002
29   Eritrea    3546.427
30  Ethiopia  114963.583

In [17]:
country.head()

Country/Region  latest_confirmed
179             US          33239963
79           India          27729247
23          Brazil          16391930
62          France           5708350
178         Turkey           5228322

### 世界全体での人口10万人あたり陽性者数

In [18]:
country.latest_confirmed.sum()

169470725

In [19]:
pop_latest.population.sum()

7794798.729

In [20]:
print("****世界全体での人口10万人あたり陽性者数:{}****".format(country.latest_confirmed.sum() / (pop_latest.population.sum() / 100)))

****世界全体での人口10万人あたり陽性者数:2174.1513911000175****


### 各国の人口１０万人あたり陽性者数

In [21]:
c_merged = pd.merge(country, pop_latest, left_on="Country/Region", right_on="country", how="left")
c_merged.loc[c_merged["country"].isna()]

Country/Region  latest_confirmed country population
0                     US          33239963     NaN        NaN
5                 Russia           4986458     NaN        NaN
12                  Iran           2886111     NaN        NaN
51               Bolivia            364570     NaN        NaN
58    West Bank and Gaza            307569     NaN        NaN
66               Moldova            255060     NaN        NaN
72             Venezuela            230147     NaN        NaN
83                 Burma            143486     NaN        NaN
84          Korea, South            139431     NaN        NaN
91                Kosovo            106946     NaN        NaN
111        Cote d'Ivoire             47195     NaN        NaN
119     Congo (Kinshasa)             31386     NaN        NaN
125                Syria             24410     NaN        NaN
143  Congo (Brazzaville)             11658     NaN        NaN
151              Taiwan*              7315     NaN        NaN
156              Vietnam              6396     NaN        NaN
174                 Laos              1905     NaN        NaN
178     Diamond Princess               712     NaN        NaN
179             Tanzania               509     NaN        NaN
181               Brunei               241     NaN        NaN
187           MS Zaandam                 9     NaN        NaN
192           Micronesia                 1     NaN        NaN

In [22]:
p_merged = pd.merge(pop_latest, country, left_on="country", right_on="Country/Region", how="left")
len(p_merged.loc[p_merged["Country/Region"].isna()])

64

In [23]:
pop_latest.loc[pop_latest["country"].str.contains("Syria")]

country population
104  Syrian Arab Republic  17500.657

In [24]:
renames = {
    "US":"United States of America",
    "Russia":"Russian Federation",
    "Iran":"Iran (Islamic Republic of)",
    "Bolivia":"Bolivia (Plurinational State of)",
    "Moldova":"Republic of Moldova",
    "Venezuela":"Venezuela (Bolivarian Republic of)",
    "Korea, South":"Republic of Korea",
    "Congo (Kinshasa)":"Democratic Republic of the Congo",
    "Congo (Brazzaville)":"Congo",
    "Vietnam":"Viet Nam",
    "Laos":"Lao People's Democratic Republic",
    "Taiwan*":"China, Taiwan Province of China",
    "Tanzania":"United Republic of Tanzania",
    "Brunei":"Brunei Darussalam",
    "Micronesia":"Micronesia (Fed. States of)",
    "Syria":"Syrian Arab Republic",
}

In [25]:
country_renamed = country.copy()
country_renamed["Country/Region"].replace(renames,inplace=True)

In [26]:
c_merged = pd.merge(country_renamed, pop_latest, left_on="Country/Region", right_on="country", how="left")
c_merged.loc[c_merged["country"].isna()]

Country/Region  latest_confirmed country population
58   West Bank and Gaza            307569     NaN        NaN
83                Burma            143486     NaN        NaN
91               Kosovo            106946     NaN        NaN
111       Cote d'Ivoire             47195     NaN        NaN
178    Diamond Princess               712     NaN        NaN
187          MS Zaandam                 9     NaN        NaN

In [27]:
c_merged["positives per 1000 population"] = c_merged["latest_confirmed"] / (c_merged["population"])
c_merged["positives per 100,000 population"] = (c_merged["latest_confirmed"] / (c_merged["population"]/100)).astype(float)

In [28]:
c_merged = c_merged.sort_values("positives per 1000 population", ascending=False)

In [29]:
c_merged.loc[c_merged["Country/Region"]=="United States of America"]

Country/Region  latest_confirmed                   country  \
0  United States of America          33239963  United States of America   

   population positives per 1000 population  positives per 100,000 population  
0  331002.647                    100.422046                      10042.204587

In [30]:
plt.figure(figsize=(9.5,5))
plt.title("positives per pupulation worst 50")
plt.xticks(rotation="90",fontsize=9)
plt.ylabel("count per 100,000 population")
#fig.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))
plt.bar(c_merged.head(50)["Country/Region"],c_merged.head(50)["positives per 100,000 population"],label="positive")
plt.legend()
plt.tight_layout()

<IPython.core.display.Javascript object>

In [31]:
c_asc = c_merged.sort_values("positives per 1000 population")
plt.figure(figsize=(9.5,5))
plt.title("positives per pupulation best 50")
plt.xticks(rotation="90",fontsize=9)
plt.ylabel("count per 100,000 population")
#fig.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))
plt.bar(c_asc.head(50)["Country/Region"],c_asc.head(50)["positives per 100,000 population"],label="positive")
plt.legend()
plt.tight_layout()

<IPython.core.display.Javascript object>

In [32]:
plt.figure(figsize=(9.5,5))
plt.title("histgram(positives per 100,000 pop)")
plt.hist(c_merged["positives per 100,000 population"],bins=[0,2000,4000,8000,10000,12000,14000,16000,18000])

<IPython.core.display.Javascript object>

(array([100.,  24.,  37.,  14.,   6.,   2.,   3.,   1.]),
 array([    0,  2000,  4000,  8000, 10000, 12000, 14000, 16000, 18000]),
 <a list of 8 Patch objects>)

In [33]:
c_merged.describe()

latest_confirmed  positives per 100,000 population
count      1.930000e+02                        187.000000
mean       8.780867e+05                       3354.065348
std        3.409928e+06                       3889.029065
min        1.000000e+00                          0.852108
25%        1.152300e+04                        185.238643
50%        9.443000e+04                       1664.838384
75%        3.916370e+05                       6206.114850
max        3.323996e+07                      17722.125154

In [34]:
c_merged.head()

Country/Region  latest_confirmed     country population  \
137        Andorra             13693     Andorra     77.265   
95      Montenegro             99518  Montenegro    628.062   
19         Czechia           1660481     Czechia  10708.982   
159     San Marino              5089  San Marino     33.938   
71         Bahrain            232425     Bahrain   1701.583   

    positives per 1000 population  positives per 100,000 population  
137                    177.221252                      17722.125154  
95                     158.452509                      15845.250947  
19                     155.054981                      15505.498095  
159                    149.949909                      14994.990866  
71                     136.593396                      13659.339568

In [35]:
c_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 193 entries, 137 to 187
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Country/Region                    193 non-null    object 
 1   latest_confirmed                  193 non-null    int64  
 2   country                           187 non-null    object 
 3   population                        187 non-null    object 
 4   positives per 1000 population     187 non-null    object 
 5   positives per 100,000 population  187 non-null    float64
dtypes: float64(1), int64(1), object(4)
memory usage: 10.6+ KB


In [36]:
plt.figure(figsize=(9.5,5))
plt.title("histgram(positives per 100,000 pop)")
plt.hist(c_merged["positives per 100,000 population"],bins=200)

<IPython.core.display.Javascript object>

/home/masaru/.pyenv/versions/anaconda3-2020.02/lib/python3.7/site-packages/numpy/lib/histograms.py:839: RuntimeWarning: invalid value encountered in greater_equal
  keep = (tmp_a >= first_edge)
/home/masaru/.pyenv/versions/anaconda3-2020.02/lib/python3.7/site-packages/numpy/lib/histograms.py:840: RuntimeWarning: invalid value encountered in less_equal
  keep &= (tmp_a <= last_edge)


(array([26., 20., 13.,  6.,  2.,  5.,  2.,  1.,  0.,  2.,  0.,  1.,  4.,
         2.,  2.,  3.,  0.,  1.,  4.,  2.,  1.,  3.,  1.,  1.,  1.,  2.,
         2.,  2.,  0.,  0.,  3.,  1.,  1.,  2.,  0.,  1.,  1.,  2.,  2.,
         0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,
         0.,  0.,  1.,  1.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,  1.,  1.,
         0.,  1.,  2.,  0.,  2.,  1.,  2.,  0.,  0.,  2.,  0.,  0.,  0.,
         2.,  1.,  4.,  1.,  0.,  0.,  3.,  1.,  0.,  1.,  2.,  1.,  1.,
         2.,  1.,  2.,  0.,  0.,  1.,  1.,  2.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.